branches:
    only:
      - master

env:
  global:
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TGZ=helm-v2.9.0-linux-amd64.tar.gz
    - GH_URL=https://porscheinformatik.github.io/helm-charts

install:
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only

script:
  - >
    for dir in `ls ${REPO_DIR}/charts`; do
      helm dep update ${REPO_DIR}/charts/$dir
      helm lint ${REPO_DIR}/charts/$dir
      helm package -d ${REPO_DIR}/build ${REPO_DIR}/charts/$dir 
    done
    helm repo index --url ${GH_URL} ${REPO_DIR}/build

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  on:
    branch: master