env:
  global:
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TGZ=helm-v2.9.0-linux-amd64.tar.gz
    - GH_URL=https://porscheinformatik.github.io/helm-charts

before_script:
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - export PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only

script:
  - git clone -b gh-pages https://github.com/porscheinformatik/helm-charts.git build
  - >
    for dir in ${TRAVIS_BUILD_DIR}/charts/*; do
      helm dep update $dir
      helm lint $dir
      helm package -d ${TRAVIS_BUILD_DIR}/build $dir
    done
  - helm repo index --url ${GH_URL} ${TRAVIS_BUILD_DIR}/build

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  on:
    branch: master