apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongodb.fullname" . }}
  labels:
    app: {{ template "mongodb.name" . }}
    chart: {{ template "mongodb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 27017
      targetPort: mongodb
      protocol: TCP
      name: http
  selector:
    app: {{ template "mongodb.name" . }}
    release: {{ .Release.Name }}
