apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "haproxy.fullname" . }}-cfg
  labels:
    app: {{ .Release.Name }}
    module: {{ template "haproxy.name" . }}
    chart: {{ template "haproxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  haproxy.cfg: |-
{{ .Values.config | indent 4 }}
