apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mariadb.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    module: {{ template "mariadb.name" . }}
    chart: {{ template "mariadb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  database-name: {{ default "sampledb" .Values.db.name | b64enc | quote }}
  database-user: {{ default "sampledb" .Values.db.user | b64enc | quote }}
  {{- if .Values.db.password }}
  database-password:  {{ .Values.db.password | b64enc | quote }}
  {{- else }}
  database-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.db.rootPassword }}
  database-root-password:  {{ .Values.db.rootPassword | b64enc | quote }}
  {{- else }}
  database-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
