# Default values for zanata.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 

image:
  repository: porscheinformatik/zanata-server
  tag: latest
  pullPolicy: Always

## Persist data to a persitent volume
persistence:
  enabled: true
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 1Gi

service:
  type: ClusterIP
  port: 8080

route:
  enabled: false
  # hostname:
  path: /zanata
  tls:
    termination: edge

mariadb:
  db:
    name: zanata
    user: zanata
    # password:

resources:
  limits:
   cpu: 800m
   memory: 1536Mi
  requests:
   cpu: 200m
   memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
