apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mongodb-replication.fullname" . }}
  labels:
    app: {{ template "mongodb-replication.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.mongodbAdminPassword }}
  mongodb-admin-password:  {{ .Values.mongodbAdminPassword | b64enc | quote }}
  {{ else }}
  mongodb-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end -}}
  {{- if .Values.mongodbPassword }}
  mongodb-password:  {{ .Values.mongodbPassword | b64enc | quote }}
  {{- else }}
  mongodb-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodbKeyFileValue }}
  mongodb-key-file-value:  {{ .Values.mongodbKeyFileValue | b64enc | quote }}
  {{- else }}
  mongodb-key-file-value: {{ randAlphaNum 255 | b64enc | quote }}
  {{- end }}

