# A non-headless service which takes pod readiness into consideration
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongodb-replication.fullname" . }}
  labels:
    app: {{ template "mongodb-replication.name" . }}
    chart: {{ template "mongodb-replication.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: mongodb          
  selector:
    app: {{ template "mongodb-replication.name" . }}
    release: {{ .Release.Name }}
    # will route traffic to pods having labels matching this selector
    name: {{ template "mongodb-replication.fullname" . }}
